## Facebook REVIEW Dataset (from Kaggle) :

In [83]:
import pandas as pd
df=pd.read_csv("C:/Users/Admin/Downloads/facebook_reviews.csv",encoding='latin-1')

In [84]:
df

,Review ID,UserName,Content,Score,ThumbsUp Count,Review Created Version,Date At,AppVersion
0,a0e37f9f-331c-4ae7-8a44-43f4202a211f,Dennis,Happy.Biryhday my friend,5,0,NaN,15-05-2024 21:58,NaN
1,9f8c42b3-dcf1-4e7f-83c4-75cbba83e0b2,BLANK TRL,Its a fake social media app that controls what...,1,3,268.1.0.54.121,15-05-2024 21:57,268.1.0.54.121
2,3a7b2259-7e98-4e2b-95ee-35f020f36039,Tisoy pogi,furf,5,0,463.1.0.53.85,15-05-2024 21:57,463.1.0.53.85
3,65bca32a-63cb-4a75-bbcc-2edcfb434f8d,jhon rey nueva,i like facebook,4,0,NaN,15-05-2024 21:56,NaN
4,5ee6896a-bff1-47d8-aac0-85c746b4ba8d,Serrius LeDamaged,Too many sponsored or suggested pages. I count...,1,3,228.0.0.41.124,15-05-2024 21:56,228.0.0.41.124
...,...,...,...,...,...,...,...,...
56109,d7816c49-b04a-4069-b9f9-25e63d069a41,Deepak thakur Deepak thakur,nice video,5,0,NaN,08-05-2024 00:07,NaN
56110,c23d2b31-4c97-41de-867c-3f5ef3a61d0d,Joseph Leblanc,love it!!!,5,0,462.0.0.47.85,08-05-2024 00:07,462.0.0.47.85
56111,01bdb728-5042-4a8f-b207-8a02263c7b3e,Christian Kelechi,Good work is confirmed,5,0,361.0.0.39.115,08-05-2024 00:07,361.0.0.39.115
56112,a5207278-bc25-4bbb-b999-004407519b81,Mankhush Abinash,I NH by t um TV ex RV hu by,1,0,462.0.0.47.85,08-05-2024 00:04,462.0.0.47.85
56113,60cb051b-de1e-4081-970b-6b7cd7e3dc03,Trudy Musgrove,Works,3,0,NaN,08-05-2024 00:01,NaN

#### Null Values

In [85]:
df.isnull().sum()

Review ID                    0
UserName                     2
Content                      8
Score                        0
ThumbsUp Count               0
Review Created Version    5830
Date At                      0
AppVersion                5830
dtype: int64

In [86]:
Total_Number_of_Null_Values = df.isnull().sum().sum()

In [87]:
Total_Number_of_Null_Values

11670

#### Filtering Data

In [88]:
df[df["AppVersion"]=="462.0.0.47.85"]

,Review ID,UserName,Content,Score,ThumbsUp Count,Review Created Version,Date At,AppVersion
7,2b4f635d-9163-48df-b676-33f327c643b0,Troy,a good way to meet new people and talk to peop...,5,0,462.0.0.47.85,15-05-2024 21:54,462.0.0.47.85
39,422a6e16-c1c8-42b8-b1bc-b14b00bc45f8,Jemba Ali,It's too interesting,5,0,462.0.0.47.85,15-05-2024 21:24,462.0.0.47.85
41,c7c739a0-5bf6-4c18-aaee-8d1adf0ff167,Stefan Pruszkiewicz,Simply perfect Ã°??Âª,5,0,462.0.0.47.85,15-05-2024 21:22,462.0.0.47.85
54,8930f292-87b4-4d2c-b1fc-79e9d8e16679,FOFO Alfa,love it,5,0,462.0.0.47.85,15-05-2024 21:11,462.0.0.47.85
105,e7900801-6ce5-45d8-9280-3e399964f140,Md Salman,public Faizal khana,5,0,462.0.0.47.85,15-05-2024 20:39,462.0.0.47.85
...,...,...,...,...,...,...,...,...
56105,97a7babf-72b5-4690-8b96-a332745eb9f9,Muhammad Rafnal,wonderful apps,5,0,462.0.0.47.85,08-05-2024 00:10,462.0.0.47.85
56107,5d4effa7-f03b-4fc4-b861-498a7824c612,A J,privacy issues,1,0,462.0.0.47.85,08-05-2024 00:09,462.0.0.47.85
56108,21347dcb-1440-4ade-a3d3-fabe9852ff6c,Bill Sweigart,I hate meta AI TAKE IT OFF OF MY ACCOUNT,2,0,462.0.0.47.85,08-05-2024 00:08,462.0.0.47.85
56110,c23d2b31-4c97-41de-867c-3f5ef3a61d0d,Joseph Leblanc,love it!!!,5,0,462.0.0.47.85,08-05-2024 00:07,462.0.0.47.85
56112,a5207278-bc25-4bbb-b999-004407519b81,Mankhush Abinash,I NH by t um TV ex RV hu by,1,0,462.0.0.47.85,08-05-2024 00:04,462.0.0.47.85

#### Filtering with Criteria

In [89]:
df[df["ThumbsUp Count"]>1000]

,Review ID,UserName,Content,Score,ThumbsUp Count,Review Created Version,Date At,AppVersion
13497,c62ccb79-ff22-4b8a-bd30-ec3ec1744788,tun tun,Thank,5,1498,NaN,11-05-2024 15:24,NaN
14549,8740f513-9024-4a6d-8caf-64a8e45d178d,Sonny R.,This app sucks and blows at the same time. It'...,1,1256,462.0.0.47.85,11-05-2024 08:40,462.0.0.47.85
15648,75bab5d0-9e93-4e58-9d30-40ec302e9751,A Google user,You are disconnecting me from my friends. The ...,1,61954,463.1.0.53.85,10-05-2024 21:49,463.1.0.53.85
16126,4727e9f6-85c7-405b-ab86-41e7c02a001e,Misty Goodrich,Sooooooo many glitches!!! From Stories to sche...,2,5258,463.1.0.53.85,10-05-2024 17:10,463.1.0.53.85
17419,0a8d809e-be47-4952-a545-4b60b6884544,Courtney Williams,I'm sooooo tired of nothing but pages and ads....,2,1242,463.0.0.45.85,10-05-2024 09:05,463.0.0.45.85
...,...,...,...,...,...,...,...,...
52390,2093e459-0ad0-47f5-a7a1-10980df523e6,Ame,THIS APP IS SO DIFFICULT TO USE!! Instructions...,1,1228,429.0.0.27.114,01-09-2023 15:45,429.0.0.27.114
52714,03381611-7602-4d34-bf4a-fefa9e68fb68,A Google user,Social media has ruined society,1,1012,462.0.0.47.85,08-05-2024 10:59,462.0.0.47.85
53676,2da70ac4-77a0-4a6c-8452-577930b8e30c,Pamela Byrge,Starting me over and over in my news feed!! Da...,1,5529,462.0.0.47.85,08-05-2024 05:01,462.0.0.47.85
54523,03381611-7602-4d34-bf4a-fefa9e68fb68,A Google user,Social media has ruined society,1,1012,462.0.0.47.85,08-05-2024 10:59,462.0.0.47.85
55485,2da70ac4-77a0-4a6c-8452-577930b8e30c,Pamela Byrge,Starting me over and over in my news feed!! Da...,1,5529,462.0.0.47.85,08-05-2024 05:01,462.0.0.47.85

#### Filtering a Row with Index (Single and Multiple)

In [90]:
df.iloc[1501] # single

Review ID                 d3a39311-fbf4-4308-a7bd-6ec384a4ef66
UserName                                            Indri devi
Content                                                   Nice
Score                                                        5
ThumbsUp Count                                               0
Review Created Version                                     NaN
Date At                                       15-05-2024 12:40
AppVersion                                                 NaN
Name: 1501, dtype: object

In [91]:
df.iloc[1501:1506] # multiple

,Review ID,UserName,Content,Score,ThumbsUp Count,Review Created Version,Date At,AppVersion
1501,d3a39311-fbf4-4308-a7bd-6ec384a4ef66,Indri devi,Nice,5,0,NaN,15-05-2024 12:40,NaN
1502,d417399f-0dd8-48f0-9528-f13b7e2a9ed3,Murari Kumar,Ok ok Ã°???,2,0,398.0.0.21.105,15-05-2024 12:39,398.0.0.21.105
1503,c72badb4-348f-4909-b69f-e0326fc08eb3,Edith Newchurch,I like Facebook because it connects me with fr...,3,0,462.0.0.47.85,15-05-2024 12:39,462.0.0.47.85
1504,a0f315c6-55c9-4829-934f-4cba9efe6ce1,Lucky Khan,nice,5,0,463.1.0.53.85,15-05-2024 12:39,463.1.0.53.85
1505,f2ffe724-60f4-4043-a063-5cc745aee78c,Rizwan Khan,Dood,5,0,461.0.0.47.85,15-05-2024 12:38,461.0.0.47.85

#### Info of the Dataset

In [92]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56114 entries, 0 to 56113
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Review ID               56114 non-null  object
 1   UserName                56112 non-null  object
 2   Content                 56106 non-null  object
 3   Score                   56114 non-null  int64
 4   ThumbsUp Count          56114 non-null  int64
 5   Review Created Version  50284 non-null  object
 6   Date At                 56114 non-null  object
 7   AppVersion              50284 non-null  object
dtypes: int64(2), object(6)
memory usage: 3.4+ MB

#### First 5 & Last 5 Values

In [93]:
df.head() # First 5 Values

,Review ID,UserName,Content,Score,ThumbsUp Count,Review Created Version,Date At,AppVersion
0,a0e37f9f-331c-4ae7-8a44-43f4202a211f,Dennis,Happy.Biryhday my friend,5,0,NaN,15-05-2024 21:58,NaN
1,9f8c42b3-dcf1-4e7f-83c4-75cbba83e0b2,BLANK TRL,Its a fake social media app that controls what...,1,3,268.1.0.54.121,15-05-2024 21:57,268.1.0.54.121
2,3a7b2259-7e98-4e2b-95ee-35f020f36039,Tisoy pogi,furf,5,0,463.1.0.53.85,15-05-2024 21:57,463.1.0.53.85
3,65bca32a-63cb-4a75-bbcc-2edcfb434f8d,jhon rey nueva,i like facebook,4,0,NaN,15-05-2024 21:56,NaN
4,5ee6896a-bff1-47d8-aac0-85c746b4ba8d,Serrius LeDamaged,Too many sponsored or suggested pages. I count...,1,3,228.0.0.41.124,15-05-2024 21:56,228.0.0.41.124

In [94]:
df.tail() # Last 5 Values

,Review ID,UserName,Content,Score,ThumbsUp Count,Review Created Version,Date At,AppVersion
56109,d7816c49-b04a-4069-b9f9-25e63d069a41,Deepak thakur Deepak thakur,nice video,5,0,NaN,08-05-2024 00:07,NaN
56110,c23d2b31-4c97-41de-867c-3f5ef3a61d0d,Joseph Leblanc,love it!!!,5,0,462.0.0.47.85,08-05-2024 00:07,462.0.0.47.85
56111,01bdb728-5042-4a8f-b207-8a02263c7b3e,Christian Kelechi,Good work is confirmed,5,0,361.0.0.39.115,08-05-2024 00:07,361.0.0.39.115
56112,a5207278-bc25-4bbb-b999-004407519b81,Mankhush Abinash,I NH by t um TV ex RV hu by,1,0,462.0.0.47.85,08-05-2024 00:04,462.0.0.47.85
56113,60cb051b-de1e-4081-970b-6b7cd7e3dc03,Trudy Musgrove,Works,3,0,NaN,08-05-2024 00:01,NaN

In [95]:
Total_Number_of_Rows_and_Columns=df.shape

In [96]:
Total_Number_of_Rows_and_Columns

(56114, 8)

In [97]:
details = df.describe()

### Stats / Insights :

In [98]:
print("Total Number of Null Values :",Total_Number_of_Null_Values)
print("Total Number of Rows and Columns :",Total_Number_of_Rows_and_Columns)
print("-"*100)
print("DETAILS :")
print(details)

Total Number of Null Values : 11670
Total Number of Rows and Columns : (56114, 8)
----------------------------------------------------------------------------------------------------
DETAILS :
              Score  ThumbsUp Count
count  56114.000000    56114.000000
mean       3.137631      103.380083
std        1.805654     1141.620850
min        1.000000        0.000000
25%        1.000000        0.000000
50%        3.000000        0.000000
75%        5.000000        1.000000
max        5.000000   110743.000000

### Data Cleaning and Missing Value Imputation :

In [99]:
import numpy as np
df

,Review ID,UserName,Content,Score,ThumbsUp Count,Review Created Version,Date At,AppVersion
0,a0e37f9f-331c-4ae7-8a44-43f4202a211f,Dennis,Happy.Biryhday my friend,5,0,NaN,15-05-2024 21:58,NaN
1,9f8c42b3-dcf1-4e7f-83c4-75cbba83e0b2,BLANK TRL,Its a fake social media app that controls what...,1,3,268.1.0.54.121,15-05-2024 21:57,268.1.0.54.121
2,3a7b2259-7e98-4e2b-95ee-35f020f36039,Tisoy pogi,furf,5,0,463.1.0.53.85,15-05-2024 21:57,463.1.0.53.85
3,65bca32a-63cb-4a75-bbcc-2edcfb434f8d,jhon rey nueva,i like facebook,4,0,NaN,15-05-2024 21:56,NaN
4,5ee6896a-bff1-47d8-aac0-85c746b4ba8d,Serrius LeDamaged,Too many sponsored or suggested pages. I count...,1,3,228.0.0.41.124,15-05-2024 21:56,228.0.0.41.124
...,...,...,...,...,...,...,...,...
56109,d7816c49-b04a-4069-b9f9-25e63d069a41,Deepak thakur Deepak thakur,nice video,5,0,NaN,08-05-2024 00:07,NaN
56110,c23d2b31-4c97-41de-867c-3f5ef3a61d0d,Joseph Leblanc,love it!!!,5,0,462.0.0.47.85,08-05-2024 00:07,462.0.0.47.85
56111,01bdb728-5042-4a8f-b207-8a02263c7b3e,Christian Kelechi,Good work is confirmed,5,0,361.0.0.39.115,08-05-2024 00:07,361.0.0.39.115
56112,a5207278-bc25-4bbb-b999-004407519b81,Mankhush Abinash,I NH by t um TV ex RV hu by,1,0,462.0.0.47.85,08-05-2024 00:04,462.0.0.47.85
56113,60cb051b-de1e-4081-970b-6b7cd7e3dc03,Trudy Musgrove,Works,3,0,NaN,08-05-2024 00:01,NaN

#### Null

In [100]:
df.isnull()

,Review ID,UserName,Content,Score,ThumbsUp Count,Review Created Version,Date At,AppVersion
0,False,False,False,False,False,True,False,True
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,True,False,True
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
56109,False,False,False,False,False,True,False,True
56110,False,False,False,False,False,False,False,False
56111,False,False,False,False,False,False,False,False
56112,False,False,False,False,False,False,False,False
56113,False,False,False,False,False,True,False,True

In [101]:
df.isnull().sum()

Review ID                    0
UserName                     2
Content                      8
Score                        0
ThumbsUp Count               0
Review Created Version    5830
Date At                      0
AppVersion                5830
dtype: int64

In [102]:
No_of_Rows = 56114
No_of_Null_Valuses = 5830
print("% TO CHECK WHETHER TO DATA CLEANING OR MISSING VALUE IMPUTATION :")
print((No_of_Null_Valuses/No_of_Rows)*100)

% TO CHECK WHETHER TO DATA CLEANING OR MISSING VALUE IMPUTATION :
10.389564101650212

#### Missing Value Imputation :

#### UserName

In [103]:
df['UserName'].unique()

array(['Dennis', 'BLANK TRL', 'Tisoy pogi', ..., 'LostGirl',
       'Pixie moonlucy', 'Karjum Koyu'], dtype=object)

In [104]:
df_mode = df.UserName.mode()[0]

In [105]:
print(df_mode)

A Google user

In [106]:
df.UserName.fillna(df_mode,inplace=True)

In [107]:
df.isnull().sum()

Review ID                    0
UserName                     0
Content                      8
Score                        0
ThumbsUp Count               0
Review Created Version    5830
Date At                      0
AppVersion                5830
dtype: int64

#### Content

In [108]:
df['Content'].unique()

array(['Happy.Biryhday my friend',
       'Its a fake social media app that controls what you can post to monopalize the information you and everyone you know to recieve fake new along with real but doctored so that its unoticed and wish to file a court case if you make a post asking friends that have told you to post to let them know that you are out of weed then then if fraud update still full of fraud and they add new algorithm to make sure you have worst time trying to fast forward through videos to see result!',
       'furf', ...,
       "Account and personal information keeps getting hacked through this app!!! I DO NOT RECOMMEND, GARBAGE Ã°???Ã¯Â¸\x8fÃ°???Ã¯Â¸\x8fÃ°???Ã¯Â¸\x8f ThRow it away Ã°??? not worth the headache and it's annoyingly old",
       "I created a Page on Facebook. Now I can't Abe to add an action button on the app. I stopped using faceore than a year ago now the app has lots of bugs. When I try to add an action button it shows a pop of something went wrong. And in the desktop websites the follow button to add as action button doesn't work at all. For this huge company this app doesn't fit well.... Very poor app and services.",
       'The recent changes has proved to be a major disadvantage'],
      dtype=object)

In [109]:
df_mode2 = df.Content.mode()[0]

In [110]:
print(df_mode2)

good

In [111]:
df.Content.fillna(df_mode2,inplace=True)

In [112]:
df.isnull().sum()

Review ID                    0
UserName                     0
Content                      0
Score                        0
ThumbsUp Count               0
Review Created Version    5830
Date At                      0
AppVersion                5830
dtype: int64

#### Review Created Version

In [121]:
df['Review Created Version'].unique()

array(['NAN', '268.1.0.54.121', '463.1.0.53.85', '228.0.0.41.124',
       '462.0.0.47.85', '463.0.0.45.85', '436.0.0.35.101',
       '451.0.0.45.109', '446.0.0.27.352', '456.0.0.39.90',
       '461.0.0.47.85', '457.0.0.54.84', '464.0.0.60.90',
       '433.0.0.31.111', '452.0.0.45.110', '420.0.0.32.61',
       '440.0.0.31.105', '459.1.0.42.84', '460.0.0.34.89',
       '418.0.0.33.69', '454.0.0.44.104', '396.1.0.28.104',
       '395.0.0.27.214', '407.0.0.30.97', '455.0.0.44.88',
       '429.0.0.27.114', '98.0.0.18.70', '308.0.0.42.118',
       '425.0.0.22.49', '431.0.0.30.108', '313.0.0.35.119',
       '450.0.0.42.110', '419.0.0.37.71', '445.0.0.34.118',
       '458.0.0.38.86', '453.0.0.40.107', '385.0.0.32.114',
       '414.0.0.30.113', '441.1.0.39.109', '322.0.0.35.121',
       '394.1.0.51.107', '376.0.0.12.108', '326.0.0.34.120',
       '449.0.0.44.115', '254.0.0.37.125', '349.0.0.39.470',
       '454.1.0.49.104', '327.0.0.33.120', '408.1.0.36.103',
       '423.0.0.21.64', '432.0.0.29.102', '239.0.0.41.152',
       '448.0.0.30.115', '409.0.0.27.106', '390.0.0.27.105',
       '287.1.0.51.119', '330.0.0.31.120', '401.0.0.24.77',
       '362.0.0.27.109', '299.0.0.51.236', '282.0.0.40.117',
       '435.0.0.42.112', '151.0.0.44.205', '422.0.0.26.76',
       '348.0.0.39.118', '312.0.0.45.117', '439.0.0.44.117',
       '77.0.0.20.66', '258.0.0.34.119', '305.1.0.40.120',
       '464.0.0.28.90', '300.1.0.57.129', '404.0.0.35.70',
       '438.0.0.33.118', '428.0.0.26.108', '295.0.0.36.119',
       '288.1.0.47.123', '411.1.0.29.112', '284.0.0.50.107',
       '398.0.0.21.105', '430.0.0.23.113', '269.0.0.50.127',
       '281.0.0.36.124', '375.1.0.28.111', '399.0.0.24.93',
       '372.1.0.23.107', '424.0.0.21.75', '412.0.0.22.115',
       '286.0.0.48.112', '201.0.0.58.99', '400.0.0.37.76',
       '396.0.0.21.104', '443.0.0.23.229', '415.0.0.34.107',
       '272.0.0.50.125', '426.0.0.26.50', '339.0.0.32.118',
       '319.0.0.39.120', '410.0.0.26.115', '382.0.0.33.111',
       '300.0.0.51.129', '279.0.0.43.120', '421.0.0.33.47',
       '89.0.0.17.70', '387.0.0.24.102', '354.0.0.22.110',
       '447.0.0.24.113', '442.0.0.44.114', '462.0.0.31.85',
       '342.0.0.37.119', '194.0.0.42.99', '303.0.0.30.122',
       '405.0.0.23.72', '416.0.0.35.85', '392.2.0.33.108',
       '318.0.0.39.154', '391.1.0.37.104', '464.0.0.6.90',
       '383.1.0.25.106', '346.0.0.29.119', '276.0.0.44.127',
       '355.0.0.21.108', '386.0.0.35.108', '365.0.0.30.112',
       '427.0.0.31.63', '338.1.0.36.118', '381.0.0.29.105',
       '360.0.0.30.113', '441.0.0.32.109', '413.0.0.30.104',
       '464.0.0.31.90', '421.0.0.30.47', '328.1.0.28.119',
       '377.0.0.22.107', '434.0.0.36.115', '285.0.0.43.120',
       '373.0.0.31.112', '307.0.0.40.111', '244.0.0.43.118',
       '335.0.0.28.118', '283.0.0.31.121', '358.0.0.34.117',
       '231.0.0.39.113', '414.0.0.32.113', '371.0.0.24.109',
       '369.0.0.18.103', '252.0.0.22.355', '397.0.0.23.404',
       '332.0.0.23.111', '337.0.0.32.118', '265.0.0.61.103',
       '106.0.0.26.68', '180.0.0.35.82', '389.0.0.42.111',
       '444.0.0.31.114', '403.0.0.27.81', '364.0.0.24.132',
       '417.0.0.33.65', '437.0.0.35.116', '124.0.0.22.66',
       '287.0.0.50.119', '334.0.0.32.119', '324.0.0.48.120',
       '356.0.0.28.112', '211.0.0.43.112', '1.9.10', '384.1.0.29.111',
       '464.0.0.17.90', '104.0.0.17.71', '340.0.0.27.113',
       '336.0.0.20.117', '152.0.0.42.136', '364.1.0.25.132',
       '464.0.0.0.55', '388.0.0.32.105', '359.0.0.30.118',
       '297.0.0.36.116', '94.0.0.13.68', '361.0.0.39.115',
       '331.1.0.29.117', '259.0.0.36.115', '230.0.0.36.117',
       '405.1.0.28.72', '393.0.0.35.106', '317.0.0.51.119',
       '352.0.0.21.117', '459.0.0.21.84', '370.0.0.23.112',
       '219.0.0.46.114', '293.0.0.43.120', '300.2.0.58.129',
       '320.0.0.34.118', '137.0.0.24.91', '122.0.0.17.71',
       '343.0.0.37.117', '451.0.0.12.109', '290.0.0.44.121',
       '181.0.0.36.82', '357.0.0.23.115', '367.2.0.26.107',
       '459.0.0.27.84', '178.0.0.57.86', '160.0.0.30.94', '406.0.0.26.90',
       '237.0.0.44.120', '341.0.0.30.73', '351.0.0.38.117',
       '378.0.0.18.112', '210.0.0.43.119', '455.0.0.0.8',
       '277.0.0.41.126', '321.0.0.37.119', '215.0.0.45.98',
       '402.1.0.24.84', '245.0.0.39.118', '374.0.0.20.109',
       '216.0.0.38.104', '379.0.0.24.109', '353.0.0.34.116',
       '220.0.0.46.112', '416.0.0.16.85', '186.0.0.48.81',
       '311.0.0.44.117', '344.0.0.34.116', '280.0.0.48.122',
       '333.0.0.30.119', '380.0.0.29.109', '81.0.0.22.70',
       '227.0.0.43.158', '273.0.0.39.123', '208.0.0.38.104',
       '250.0.0.26.241', '278.0.0.51.119', '310.0.0.50.118',
       '275.0.0.49.127', '255.0.0.33.121', '161.0.0.35.93',
       '16.0.0.20.15', '50.0.0.10.54', '329.0.0.29.120', '156.0.0.22.100',
       '298.0.0.46.116', '3.9', '222.0.0.48.113', '249.0.0.47.118',
       '261.0.0.52.126', '223.0.0.47.120', '325.0.0.36.170',
       '463.0.0.30.85', '463.0.0.0.50', '465.0.0.0.6', '289.0.0.40.121',
       '251.0.0.31.111', '315.0.0.47.113', '147.0.0.44.75',
       '363.0.0.30.112', '368.0.0.24.108', '345.0.0.34.118',
       '274.0.0.46.119', '257.0.0.44.118', '56.0.0.23.68',
       '328.0.0.22.119', '253.0.0.28.116', '463.0.0.5.85',
       '316.0.0.54.116', '135.0.0.4.90', '310.0.0.0.83', '240.0.0.38.121',
       '3.4', '247.0.0.42.116', '401.0.0.25.77', '205.0.0.27.113',
       '323.0.0.46.119', '454.0.0.23.104', '195.0.0.35.99',
       '459.1.0.41.84', '459.0.0.38.84', '459.0.0.1.84', '459.0.0.26.84',
       '455.0.0.26.88', '445.0.0.35.118', '458.0.0.0.5', '457.0.0.3.84',
       '347.0.0.28.237', '444.0.0.0.4', '309.0.0.47.119',
       '367.0.0.24.107', '214.0.0.43.83', '455.0.0.0.51',
       '454.0.0.30.104', '242.0.0.43.119', '153.0.0.54.88',
       '460.0.0.1.89', '141.0.0.31.91', '170.0.0.52.95', '443.0.0.1.229',
       '460.0.0.19.89', '200.0.0.50.194', '198.0.0.53.101',
       '271.0.0.55.109', '196.0.0.41.95', '202.0.0.40.99',
       '238.0.0.41.116', '190.0.0.34.94', '217.0.0.45.98',
       '304.0.0.42.118', '260.0.0.42.118', '221.0.0.48.102',
       '157.0.0.38.97', '125.0.0.23.80', '206.0.0.36.105',
       '204.0.0.24.101', '121.0.0.20.69', '191.0.0.35.96',
       '197.0.0.46.98', '193.0.0.45.101', '226.0.0.49.120',
       '294.0.0.39.118', '187.0.0.43.81', '189.0.0.35.91',
       '165.0.0.53.93', '203.0.0.16.293', '225.0.0.47.118',
       '171.0.0.49.92', '243.0.0.49.108', '248.1.0.44.116',
       '232.0.0.35.115', '207.0.0.33.100', '188.0.0.44.81',
       '270.1.0.66.127', '263.0.0.46.121', '256.0.0.39.117',
       '184.0.0.41.79', '150.0.0.38.138', '301.0.0.37.477',
       '148.0.0.51.62', '85.0.0.15.70', '314.0.0.43.119', '100.0.0.20.70',
       '218.0.0.46.109', '262.0.0.34.117', '183.0.0.39.75',
       '156.0.0.36.100', '350.1.0.29.106', '192.0.0.34.85',
       '113.0.0.16.70', '199.0.0.56.98', '292.0.0.60.123',
       '198.0.0.28.101', '243.0.0.47.108', '236.0.0.40.117',
       '163.0.0.43.91', '292.0.0.61.123', '234.0.0.30.115',
       '212.0.0.28.110', '173.0.0.62.99', '224.0.0.33.114',
       '291.0.0.44.120', '178.0.0.48.86', '3.5', '107.0.0.19.337',
       '130.0.0.45.70', '246.0.0.49.121', '67.0.0.21.154',
       '264.0.0.44.111', '296.0.0.44.119', '143.0.0.32.90',
       '235.0.0.38.118', '302.0.0.45.119', '366.1.0.20.113',
       '233.0.0.36.117', '241.0.0.39.120', '1.0.7', '159.0.0.38.95',
       '183.0.0.57.75', '1.6.5', '133.0.0.19.83', '65.0.0.42.81',
       '82.0.0.23.70', '266.0.0.64.124', '306.1.0.40.119',
       '182.0.0.46.77', '131.0.0.32.69', '444.0.0.0.8', '168.0.0.40.90',
       '129.0.0.29.67', '304.0.0.39.118', '266.0.0.56.124',
       '110.0.0.15.69', '18.0.0.24.14', '169.0.0.46.94', '209.0.0.39.91',
       '267.1.0.46.120', '314.1.0.45.119', '270.0.0.57.127',
       '162.0.0.45.94', '456.0.0.0.21', '229.0.0.35.117', '94.0.0.17.68',
       '444.0.0.2.114', '158.0.0.38.95', '185.0.0.27.72', '455.0.0.0.35',
       '93.0.0.13.69', '402.0.0.21.84', '149.0.0.40.71', '96.0.0.17.70',
       '175.0.0.40.97', '221.0.0.41.102', '457.0.0.0.9', '33.0.0.45.19',
       '154.0.0.33.385', '28.0.0.20.16', '135.0.0.22.90', '174.0.0.54.96',
       '97.0.0.18.69', '185.0.0.39.72', '195.0.0.34.99', '9.0.0.26.28',
       '1.9.6', '120.0.0.18.72', '108.0.0.17.68', '176.0.0.42.87',
       '144.0.0.27.91', '139.0.0.26.93', '379.0.0.2.109', '132.0.0.20.85',
       '434.0.0.1.115', '455.0.0.10.88', '180.0.0.29.82', '182.0.0.44.77',
       '151.0.0.40.205', '1.9.12', '57.0.0.18.136', '426.0.0.0.32',
       '32.0.0.23.15', '128.0.0.26.68', '179.0.0.44.83', '448.0.0.5.115',
       '443.0.0.6.229', '19.0.0.28.14', '394.0.0.40.107', '52.0.0.12.18',
       '101.0.0.18.70', '109.0.0.15.71', '157.0.0.17.97', '1.8.3',
       '19.0.0.24.14', '127.0.0.22.69', '40.0.0.24.199', '24.0.0.30.15',
       '92.0.0.16.72', '43.0.0.29.147', '384.0.0.25.111', '136.0.0.22.91',
       '84.0.0.20.70', '103.0.0.20.72', '102.0.0.28.70', '216.0.0.4.104',
       '1.8.4', '198.0.0.48.101', '306.0.0.38.119', '393.0.0.34.106',
       '111.0.0.18.69', '449.0.0.13.115', '361.0.0.20.115', '1.0.10',
       '379.0.0.1.109', '225.0.0.8.118', '45.0.0.38.146', '34.0.0.43.267',
       '318.0.0.3.154', '12.0.0.15.14', '7.0.0.22.28'], dtype=object)

In [113]:
df['Review Created Version'] = df['Review Created Version'].fillna('NAN')

In [114]:
df.isnull().sum()

Review ID                    0
UserName                     0
Content                      0
Score                        0
ThumbsUp Count               0
Review Created Version       0
Date At                      0
AppVersion                5830
dtype: int64

#### AppVersion

In [115]:
df['AppVersion'].unique()

array([nan, '268.1.0.54.121', '463.1.0.53.85', '228.0.0.41.124',
       '462.0.0.47.85', '463.0.0.45.85', '436.0.0.35.101',
       '451.0.0.45.109', '446.0.0.27.352', '456.0.0.39.90',
       '461.0.0.47.85', '457.0.0.54.84', '464.0.0.60.90',
       '433.0.0.31.111', '452.0.0.45.110', '420.0.0.32.61',
       '440.0.0.31.105', '459.1.0.42.84', '460.0.0.34.89',
       '418.0.0.33.69', '454.0.0.44.104', '396.1.0.28.104',
       '395.0.0.27.214', '407.0.0.30.97', '455.0.0.44.88',
       '429.0.0.27.114', '98.0.0.18.70', '308.0.0.42.118',
       '425.0.0.22.49', '431.0.0.30.108', '313.0.0.35.119',
       '450.0.0.42.110', '419.0.0.37.71', '445.0.0.34.118',
       '458.0.0.38.86', '453.0.0.40.107', '385.0.0.32.114',
       '414.0.0.30.113', '441.1.0.39.109', '322.0.0.35.121',
       '394.1.0.51.107', '376.0.0.12.108', '326.0.0.34.120',
       '449.0.0.44.115', '254.0.0.37.125', '349.0.0.39.470',
       '454.1.0.49.104', '327.0.0.33.120', '408.1.0.36.103',
       '423.0.0.21.64', '432.0.0.29.102', '239.0.0.41.152',
       '448.0.0.30.115', '409.0.0.27.106', '390.0.0.27.105',
       '287.1.0.51.119', '330.0.0.31.120', '401.0.0.24.77',
       '362.0.0.27.109', '299.0.0.51.236', '282.0.0.40.117',
       '435.0.0.42.112', '151.0.0.44.205', '422.0.0.26.76',
       '348.0.0.39.118', '312.0.0.45.117', '439.0.0.44.117',
       '77.0.0.20.66', '258.0.0.34.119', '305.1.0.40.120',
       '464.0.0.28.90', '300.1.0.57.129', '404.0.0.35.70',
       '438.0.0.33.118', '428.0.0.26.108', '295.0.0.36.119',
       '288.1.0.47.123', '411.1.0.29.112', '284.0.0.50.107',
       '398.0.0.21.105', '430.0.0.23.113', '269.0.0.50.127',
       '281.0.0.36.124', '375.1.0.28.111', '399.0.0.24.93',
       '372.1.0.23.107', '424.0.0.21.75', '412.0.0.22.115',
       '286.0.0.48.112', '201.0.0.58.99', '400.0.0.37.76',
       '396.0.0.21.104', '443.0.0.23.229', '415.0.0.34.107',
       '272.0.0.50.125', '426.0.0.26.50', '339.0.0.32.118',
       '319.0.0.39.120', '410.0.0.26.115', '382.0.0.33.111',
       '300.0.0.51.129', '279.0.0.43.120', '421.0.0.33.47',
       '89.0.0.17.70', '387.0.0.24.102', '354.0.0.22.110',
       '447.0.0.24.113', '442.0.0.44.114', '462.0.0.31.85',
       '342.0.0.37.119', '194.0.0.42.99', '303.0.0.30.122',
       '405.0.0.23.72', '416.0.0.35.85', '392.2.0.33.108',
       '318.0.0.39.154', '391.1.0.37.104', '464.0.0.6.90',
       '383.1.0.25.106', '346.0.0.29.119', '276.0.0.44.127',
       '355.0.0.21.108', '386.0.0.35.108', '365.0.0.30.112',
       '427.0.0.31.63', '338.1.0.36.118', '381.0.0.29.105',
       '360.0.0.30.113', '441.0.0.32.109', '413.0.0.30.104',
       '464.0.0.31.90', '421.0.0.30.47', '328.1.0.28.119',
       '377.0.0.22.107', '434.0.0.36.115', '285.0.0.43.120',
       '373.0.0.31.112', '307.0.0.40.111', '244.0.0.43.118',
       '335.0.0.28.118', '283.0.0.31.121', '358.0.0.34.117',
       '231.0.0.39.113', '414.0.0.32.113', '371.0.0.24.109',
       '369.0.0.18.103', '252.0.0.22.355', '397.0.0.23.404',
       '332.0.0.23.111', '337.0.0.32.118', '265.0.0.61.103',
       '106.0.0.26.68', '180.0.0.35.82', '389.0.0.42.111',
       '444.0.0.31.114', '403.0.0.27.81', '364.0.0.24.132',
       '417.0.0.33.65', '437.0.0.35.116', '124.0.0.22.66',
       '287.0.0.50.119', '334.0.0.32.119', '324.0.0.48.120',
       '356.0.0.28.112', '211.0.0.43.112', '1.9.10', '384.1.0.29.111',
       '464.0.0.17.90', '104.0.0.17.71', '340.0.0.27.113',
       '336.0.0.20.117', '152.0.0.42.136', '364.1.0.25.132',
       '464.0.0.0.55', '388.0.0.32.105', '359.0.0.30.118',
       '297.0.0.36.116', '94.0.0.13.68', '361.0.0.39.115',
       '331.1.0.29.117', '259.0.0.36.115', '230.0.0.36.117',
       '405.1.0.28.72', '393.0.0.35.106', '317.0.0.51.119',
       '352.0.0.21.117', '459.0.0.21.84', '370.0.0.23.112',
       '219.0.0.46.114', '293.0.0.43.120', '300.2.0.58.129',
       '320.0.0.34.118', '137.0.0.24.91', '122.0.0.17.71',
       '343.0.0.37.117', '451.0.0.12.109', '290.0.0.44.121',
       '181.0.0.36.82', '357.0.0.23.115', '367.2.0.26.107',
       '459.0.0.27.84', '178.0.0.57.86', '160.0.0.30.94', '406.0.0.26.90',
       '237.0.0.44.120', '341.0.0.30.73', '351.0.0.38.117',
       '378.0.0.18.112', '210.0.0.43.119', '455.0.0.0.8',
       '277.0.0.41.126', '321.0.0.37.119', '215.0.0.45.98',
       '402.1.0.24.84', '245.0.0.39.118', '374.0.0.20.109',
       '216.0.0.38.104', '379.0.0.24.109', '353.0.0.34.116',
       '220.0.0.46.112', '416.0.0.16.85', '186.0.0.48.81',
       '311.0.0.44.117', '344.0.0.34.116', '280.0.0.48.122',
       '333.0.0.30.119', '380.0.0.29.109', '81.0.0.22.70',
       '227.0.0.43.158', '273.0.0.39.123', '208.0.0.38.104',
       '250.0.0.26.241', '278.0.0.51.119', '310.0.0.50.118',
       '275.0.0.49.127', '255.0.0.33.121', '161.0.0.35.93',
       '16.0.0.20.15', '50.0.0.10.54', '329.0.0.29.120', '156.0.0.22.100',
       '298.0.0.46.116', '3.9', '222.0.0.48.113', '249.0.0.47.118',
       '261.0.0.52.126', '223.0.0.47.120', '325.0.0.36.170',
       '463.0.0.30.85', '463.0.0.0.50', '465.0.0.0.6', '289.0.0.40.121',
       '251.0.0.31.111', '315.0.0.47.113', '147.0.0.44.75',
       '363.0.0.30.112', '368.0.0.24.108', '345.0.0.34.118',
       '274.0.0.46.119', '257.0.0.44.118', '56.0.0.23.68',
       '328.0.0.22.119', '253.0.0.28.116', '463.0.0.5.85',
       '316.0.0.54.116', '135.0.0.4.90', '310.0.0.0.83', '240.0.0.38.121',
       '3.4', '247.0.0.42.116', '401.0.0.25.77', '205.0.0.27.113',
       '323.0.0.46.119', '454.0.0.23.104', '195.0.0.35.99',
       '459.1.0.41.84', '459.0.0.38.84', '459.0.0.1.84', '459.0.0.26.84',
       '455.0.0.26.88', '445.0.0.35.118', '458.0.0.0.5', '457.0.0.3.84',
       '347.0.0.28.237', '444.0.0.0.4', '309.0.0.47.119',
       '367.0.0.24.107', '214.0.0.43.83', '455.0.0.0.51',
       '454.0.0.30.104', '242.0.0.43.119', '153.0.0.54.88',
       '460.0.0.1.89', '141.0.0.31.91', '170.0.0.52.95', '443.0.0.1.229',
       '460.0.0.19.89', '200.0.0.50.194', '198.0.0.53.101',
       '271.0.0.55.109', '196.0.0.41.95', '202.0.0.40.99',
       '238.0.0.41.116', '190.0.0.34.94', '217.0.0.45.98',
       '304.0.0.42.118', '260.0.0.42.118', '221.0.0.48.102',
       '157.0.0.38.97', '125.0.0.23.80', '206.0.0.36.105',
       '204.0.0.24.101', '121.0.0.20.69', '191.0.0.35.96',
       '197.0.0.46.98', '193.0.0.45.101', '226.0.0.49.120',
       '294.0.0.39.118', '187.0.0.43.81', '189.0.0.35.91',
       '165.0.0.53.93', '203.0.0.16.293', '225.0.0.47.118',
       '171.0.0.49.92', '243.0.0.49.108', '248.1.0.44.116',
       '232.0.0.35.115', '207.0.0.33.100', '188.0.0.44.81',
       '270.1.0.66.127', '263.0.0.46.121', '256.0.0.39.117',
       '184.0.0.41.79', '150.0.0.38.138', '301.0.0.37.477',
       '148.0.0.51.62', '85.0.0.15.70', '314.0.0.43.119', '100.0.0.20.70',
       '218.0.0.46.109', '262.0.0.34.117', '183.0.0.39.75',
       '156.0.0.36.100', '350.1.0.29.106', '192.0.0.34.85',
       '113.0.0.16.70', '199.0.0.56.98', '292.0.0.60.123',
       '198.0.0.28.101', '243.0.0.47.108', '236.0.0.40.117',
       '163.0.0.43.91', '292.0.0.61.123', '234.0.0.30.115',
       '212.0.0.28.110', '173.0.0.62.99', '224.0.0.33.114',
       '291.0.0.44.120', '178.0.0.48.86', '3.5', '107.0.0.19.337',
       '130.0.0.45.70', '246.0.0.49.121', '67.0.0.21.154',
       '264.0.0.44.111', '296.0.0.44.119', '143.0.0.32.90',
       '235.0.0.38.118', '302.0.0.45.119', '366.1.0.20.113',
       '233.0.0.36.117', '241.0.0.39.120', '1.0.7', '159.0.0.38.95',
       '183.0.0.57.75', '1.6.5', '133.0.0.19.83', '65.0.0.42.81',
       '82.0.0.23.70', '266.0.0.64.124', '306.1.0.40.119',
       '182.0.0.46.77', '131.0.0.32.69', '444.0.0.0.8', '168.0.0.40.90',
       '129.0.0.29.67', '304.0.0.39.118', '266.0.0.56.124',
       '110.0.0.15.69', '18.0.0.24.14', '169.0.0.46.94', '209.0.0.39.91',
       '267.1.0.46.120', '314.1.0.45.119', '270.0.0.57.127',
       '162.0.0.45.94', '456.0.0.0.21', '229.0.0.35.117', '94.0.0.17.68',
       '444.0.0.2.114', '158.0.0.38.95', '185.0.0.27.72', '455.0.0.0.35',
       '93.0.0.13.69', '402.0.0.21.84', '149.0.0.40.71', '96.0.0.17.70',
       '175.0.0.40.97', '221.0.0.41.102', '457.0.0.0.9', '33.0.0.45.19',
       '154.0.0.33.385', '28.0.0.20.16', '135.0.0.22.90', '174.0.0.54.96',
       '97.0.0.18.69', '185.0.0.39.72', '195.0.0.34.99', '9.0.0.26.28',
       '1.9.6', '120.0.0.18.72', '108.0.0.17.68', '176.0.0.42.87',
       '144.0.0.27.91', '139.0.0.26.93', '379.0.0.2.109', '132.0.0.20.85',
       '434.0.0.1.115', '455.0.0.10.88', '180.0.0.29.82', '182.0.0.44.77',
       '151.0.0.40.205', '1.9.12', '57.0.0.18.136', '426.0.0.0.32',
       '32.0.0.23.15', '128.0.0.26.68', '179.0.0.44.83', '448.0.0.5.115',
       '443.0.0.6.229', '19.0.0.28.14', '394.0.0.40.107', '52.0.0.12.18',
       '101.0.0.18.70', '109.0.0.15.71', '157.0.0.17.97', '1.8.3',
       '19.0.0.24.14', '127.0.0.22.69', '40.0.0.24.199', '24.0.0.30.15',
       '92.0.0.16.72', '43.0.0.29.147', '384.0.0.25.111', '136.0.0.22.91',
       '84.0.0.20.70', '103.0.0.20.72', '102.0.0.28.70', '216.0.0.4.104',
       '1.8.4', '198.0.0.48.101', '306.0.0.38.119', '393.0.0.34.106',
       '111.0.0.18.69', '449.0.0.13.115', '361.0.0.20.115', '1.0.10',
       '379.0.0.1.109', '225.0.0.8.118', '45.0.0.38.146', '34.0.0.43.267',
       '318.0.0.3.154', '12.0.0.15.14', '7.0.0.22.28'], dtype=object)

In [122]:
df['Review Created Version'] = df['Review Created Version'].fillna('NAN')

In [119]:
df.isnull().sum()

Review ID                 0
UserName                  0
Content                   0
Score                     0
ThumbsUp Count            0
Review Created Version    0
Date At                   0
AppVersion                0
dtype: int64

## Final DATASET :

In [123]:
df

,Review ID,UserName,Content,Score,ThumbsUp Count,Review Created Version,Date At,AppVersion
0,a0e37f9f-331c-4ae7-8a44-43f4202a211f,Dennis,Happy.Biryhday my friend,5,0,NAN,15-05-2024 21:58,462.0.0.47.85
1,9f8c42b3-dcf1-4e7f-83c4-75cbba83e0b2,BLANK TRL,Its a fake social media app that controls what...,1,3,268.1.0.54.121,15-05-2024 21:57,268.1.0.54.121
2,3a7b2259-7e98-4e2b-95ee-35f020f36039,Tisoy pogi,furf,5,0,463.1.0.53.85,15-05-2024 21:57,463.1.0.53.85
3,65bca32a-63cb-4a75-bbcc-2edcfb434f8d,jhon rey nueva,i like facebook,4,0,NAN,15-05-2024 21:56,462.0.0.47.85
4,5ee6896a-bff1-47d8-aac0-85c746b4ba8d,Serrius LeDamaged,Too many sponsored or suggested pages. I count...,1,3,228.0.0.41.124,15-05-2024 21:56,228.0.0.41.124
...,...,...,...,...,...,...,...,...
56109,d7816c49-b04a-4069-b9f9-25e63d069a41,Deepak thakur Deepak thakur,nice video,5,0,NAN,08-05-2024 00:07,462.0.0.47.85
56110,c23d2b31-4c97-41de-867c-3f5ef3a61d0d,Joseph Leblanc,love it!!!,5,0,462.0.0.47.85,08-05-2024 00:07,462.0.0.47.85
56111,01bdb728-5042-4a8f-b207-8a02263c7b3e,Christian Kelechi,Good work is confirmed,5,0,361.0.0.39.115,08-05-2024 00:07,361.0.0.39.115
56112,a5207278-bc25-4bbb-b999-004407519b81,Mankhush Abinash,I NH by t um TV ex RV hu by,1,0,462.0.0.47.85,08-05-2024 00:04,462.0.0.47.85
56113,60cb051b-de1e-4081-970b-6b7cd7e3dc03,Trudy Musgrove,Works,3,0,NAN,08-05-2024 00:01,462.0.0.47.85